# Generated by Django 5.2.4 on 2025-11-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='기사 제목')),
                ('link', models.URLField(max_length=1000, unique=True, verbose_name='기사 링크')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='RSS 요약')),
                ('published_at', models.DateTimeField(verbose_name='발행 일시')),
                ('content', models.TextField(blank=True, null=True, verbose_name='기사 본문 전체')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='감정 점수')),
                ('topics', models.JSONField(blank=True, null=True, verbose_name='주요 토픽')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-published_at'],
            },
        ),
    ]
