# Generated by Django 5.2.9 on 2025-12-21 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=50)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('market_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', 'time'], name='idx_stockprice_stock_time')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'time'), name='uq_stockprice_stock_time')],
            },
        ),
    ]
